export const KNX_CONSTANTS = {
  DEFAULT_MULTICAST_ADDRESS: '224.0.23.12',
  DEFAULT_PORT: 3671,
  HEADER_SIZE: 6,
  KNXNETIP_VERSION: 0x10,
  
  SERVICE_TYPES: {
    ROUTING_INDICATION: 0x0530,
    ROUTING_LOST_MESSAGE: 0x0531,
    ROUTING_BUSY: 0x0532
  },
  
  CEMI_MESSAGE_CODES: {
    L_DATA_REQ: 0x11,
    L_DATA_CON: 0x2E,
    L_DATA_IND: 0x29
  },
  
  ROUTING_COUNTER: {
    MIN: 0,
    MAX: 6,
    DONT_ROUTE: 0,
    DONT_DECREMENT: 7
  },
  
  FLOW_CONTROL: {
    MIN_WAIT_TIME: 20,
    MAX_WAIT_TIME: 100,
    DEFAULT_PROCESS_TIME: 100,
    RANDOM_FACTOR: 50,
    BUSY_DECREMENT_INTERVAL: 5,
    BUSY_DETECTION_THRESHOLD: 10
  }
} as const;